alias eng='LANG=C LANGUAGE=C LC_ALL=C'
alias grep='grep --color=auto --color=always'
alias less='less -R'
alias l.='ls .[a-zA-Z]* -G'
alias la='ls -aG'
alias ll='ls -laG'
alias ls='ls -FG'
alias spidermonkey='js'
